# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly_classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('classifier_type', models.TextField(blank=True)),
                ('threshold', models.FloatField(blank=True)),
                ('configuration_dict', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_index', models.TextField()),
                ('record_time', models.DateTimeField()),
                ('int_value', models.FloatField(blank=True)),
                ('text_field', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_analyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user_id', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('num_text_field', models.IntegerField(default=0)),
                ('num_int_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('F1', models.FloatField(blank=True)),
                ('F2', models.FloatField(blank=True)),
                ('F3', models.FloatField(blank=True)),
                ('F4', models.FloatField(blank=True)),
                ('F5', models.FloatField(blank=True)),
                ('F6', models.FloatField(blank=True)),
                ('F7', models.FloatField(blank=True)),
                ('F8', models.FloatField(blank=True)),
                ('F9', models.FloatField(blank=True)),
                ('F10', models.FloatField(blank=True)),
                ('F11', models.FloatField(blank=True)),
                ('F12', models.FloatField(blank=True)),
                ('F13', models.FloatField(blank=True)),
                ('F14', models.FloatField(blank=True)),
                ('F15', models.FloatField(blank=True)),
                ('F16', models.FloatField(blank=True)),
                ('F17', models.FloatField(blank=True)),
                ('F18', models.FloatField(blank=True)),
                ('F19', models.FloatField(blank=True)),
                ('F20', models.FloatField(blank=True)),
                ('F21', models.TextField(blank=True)),
                ('F22', models.TextField(blank=True)),
                ('F23', models.TextField(blank=True)),
                ('F24', models.TextField(blank=True)),
                ('F25', models.TextField(blank=True)),
                ('F26', models.TextField(blank=True)),
                ('F27', models.TextField(blank=True)),
                ('F28', models.TextField(blank=True)),
                ('F29', models.TextField(blank=True)),
                ('F30', models.TextField(blank=True)),
                ('data_analyzer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Data_analyzer')),
            ],
        ),
        migrations.CreateModel(
            name='Data_record_attribute_hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
                ('actu_name', models.TextField()),
                ('data_analyzer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Data_analyzer')),
            ],
        ),
        migrations.CreateModel(
            name='Detection_algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_index', models.TextField()),
                ('algorithm_path', models.TextField()),
                ('algorithm_description', models.TextField(blank=True)),
                ('data_analyzer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Data_analyzer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('authority', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_accessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analyzer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Data_analyzer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.User')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly_record',
            name='data_record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Data_record'),
        ),
        migrations.AddField(
            model_name='anomaly_classifier',
            name='data_record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Data_record'),
        ),
    ]
